version: "3.8"
services:
  greeting:
    build: greeter-service
    container_name: greeter
    environment:
      - "GENERATOR_MP_REST_URL=http://greeting_generator:8080/generator/resources"
      - "JAEGER_HOST=jaeger"
    ports:
      - 8080:8080
      - 9990:9990
  genarator:
    build: generator
    container_name: greeting_generator
    environment:
      - "JAEGER_HOST=jaeger"
    ports:
    - 8081:8080
    - 9991:9990
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "14268:14268"
      - "16686:16686"